package me.johnnywoof.check;

public enum CheckType {

    FLY, NOSWING, SPEED_BREAK, GOD_MODE, CRITICAL, ATTACK_REACH, ATTACK_SPEED, FAST_THROW, VERTICAL_SPEED, HORIZONTAL_SPEED, TIMER, SPAM, AUTOSIGN, SPEED_CLICK, AUTOSOUP, NOFALL, FAST_INTERACT, GLIDE, FULLBRIGHT, NOKNOCKBACK, FAST_BOW, FIGHT_KNOCKBACK, FAST_EAT,
    IMPOSSIBLE_MOVE, IMPOSSIBLE_CLICK, IMPOSSIBLE_CHAT, IMPOSSIBLE_FIGHT, BLOCK_VISIBLE, FIGHT_VISIBLE, FAST_BREAK;

}
