package me.johnnywoof.check;

public enum CheckType {

	FLY, IMPOSSIBLE, FASTPLACE, NOSWING, SPEED_BREAK, GOD_MODE, CRITICAL, ATTACK_REACH, ATTACK_SPEED, AIMBOT, FAST_THROW, VERTICAL_SPEED, HORIZONTAL_SPEED
	, TIMER, SPAM, FASTCLICK, AUTOSOUP, VISIBLE, NOFALL, FAST_INTERACT, GLIDE, FULLBRIGHT, NOKNOCKBACK, FAST_BOW, FIGHT_KNOCKBACK, FAST_EAT;
	
}
